const Trails = {
  // ── FREE ─────────────────────────────────────────────
  none: {
    name: 'Default',
    cost: 0,
    desc: 'Basic trail',
    type: 'default',
  },

  // ── BASIC (cheap, gentle color trails) ───────────────
  ember: {
    name: 'Ember',
    cost: 50,
    desc: 'Warm orange sparks',
    type: 'particles',
    colors: ['#ff6622', '#ff9944', '#ffcc44'],
    particleSize: [1.5, 3.5],
    rate: 2,
    lifetime: 0.8,
    gravity: 12,
    spread: 5,
  },
  frost: {
    name: 'Frost',
    cost: 50,
    desc: 'Icy crystal dust',
    type: 'particles',
    colors: ['#aaeeff', '#66ddff', '#ffffff'],
    particleSize: [1, 3],
    rate: 2,
    lifetime: 1.0,
    gravity: -6,
    spread: 6,
  },
  toxic: {
    name: 'Toxic',
    cost: 60,
    desc: 'Green poison drip',
    type: 'particles',
    colors: ['#44ff44', '#22cc22', '#88ff88'],
    particleSize: [1.5, 3.5],
    rate: 2,
    lifetime: 0.8,
    gravity: 20,
    spread: 4,
  },
  bubblegum: {
    name: 'Bubblegum',
    cost: 60,
    desc: 'Pink floating bubbles',
    type: 'bubbles',
    colors: ['#ff66aa', '#ff88cc', '#ffaadd'],
    particleSize: [2, 5],
    rate: 2,
    lifetime: 1.2,
    gravity: -8,
    spread: 6,
  },

  // ── MID TIER ─────────────────────────────────────────
  lightning: {
    name: 'Lightning',
    cost: 130,
    desc: 'Soft electric sparks',
    type: 'lightning',
    colors: ['#44ccff', '#88eeff', '#ffffff'],
    particleSize: [0.5, 2],
    rate: 2,
    lifetime: 0.4,
    gravity: 0,
    spread: 8,
  },
  stardust: {
    name: 'Stardust',
    cost: 130,
    desc: 'Twinkling star sparkles',
    type: 'stars',
    colors: ['#ffd700', '#ffee88', '#ffffff'],
    particleSize: [2, 4],
    rate: 2,
    lifetime: 1.2,
    gravity: -3,
    spread: 8,
  },
  shadow: {
    name: 'Shadow',
    cost: 150,
    desc: 'Dark afterimages linger',
    type: 'afterimage',
    colors: ['#222244', '#443366', '#665588'],
    particleSize: [3, 6],
    rate: 2,
    lifetime: 1.0,
    gravity: 0,
    spread: 3,
  },
  petals: {
    name: 'Cherry Blossom',
    cost: 175,
    desc: 'Drifting sakura petals',
    type: 'petals',
    colors: ['#ffaacc', '#ff88bb', '#ffccdd', '#ffffff'],
    particleSize: [2, 5],
    rate: 2,
    lifetime: 1.5,
    gravity: 8,
    spread: 10,
  },

  // ── PREMIUM (animated, subtle complex effects) ──────
  rainbow: {
    name: 'Rainbow',
    cost: 350,
    desc: 'Shifting prismatic ribbon',
    type: 'rainbow',
    premium: true,
    colors: [],
    particleSize: [2, 4],
    rate: 3,
    lifetime: 1.0,
    gravity: 0,
    spread: 4,
  },
  nebula: {
    name: 'Nebula',
    cost: 400,
    desc: 'Swirling cosmic gas wisps',
    type: 'nebula',
    premium: true,
    colors: ['#9944ff', '#ff44aa', '#4488ff', '#44ffaa'],
    particleSize: [4, 8],
    rate: 2,
    lifetime: 1.5,
    gravity: 0,
    spread: 10,
  },
  inferno: {
    name: 'Inferno',
    cost: 400,
    desc: 'Gentle flame glow',
    type: 'inferno',
    premium: true,
    colors: ['#ff2200', '#ff6600', '#ffaa00', '#ffee44'],
    smokeColors: ['#333333', '#555555', '#444444'],
    particleSize: [2, 5],
    rate: 3,
    lifetime: 0.8,
    gravity: -15,
    spread: 6,
  },
  void: {
    name: 'Void Rift',
    cost: 400,
    desc: 'Subtle reality distortion',
    type: 'void',
    premium: true,
    colors: ['#110022', '#220044', '#440088', '#8800ff'],
    particleSize: [3, 7],
    rate: 2,
    lifetime: 1.0,
    gravity: 0,
    spread: 5,
  },
  glitch: {
    name: 'Glitch',
    cost: 400,
    desc: 'Digital distortion fragments',
    type: 'glitch',
    premium: true,
    colors: ['#00ff00', '#ff0000', '#0000ff', '#ffffff'],
    particleSize: [1.5, 4],
    rate: 3,
    lifetime: 0.5,
    gravity: 0,
    spread: 8,
  },
  aurora: {
    name: 'Aurora',
    cost: 500,
    desc: 'Soft northern lights glow',
    type: 'aurora',
    premium: true,
    colors: ['#44ff88', '#44ddff', '#aa44ff', '#ff44aa'],
    particleSize: [4, 8],
    rate: 3,
    lifetime: 1.5,
    gravity: -4,
    spread: 12,
  },
};

export default Trails;
